'use strict';
let homepageUsers=null,homepageUsersRevision=0,homepageUsersLoading=false,homepageUsersError='';
function homepageAddress(){const url=new URL(location.href);url.protocol='http:';url.port=config.homepage.port;url.pathname='/';url.search='';url.hash='';return url.href;}
async function loadHomepageUsers(){if(homepageUsersLoading)return;homepageUsersLoading=true;homepageUsersError='';try{const result=await api('homepage/users');homepageUsers=result.users;homepageUsersRevision=result.revision;}catch(error){homepageUsersError=error.message;}finally{homepageUsersLoading=false;if(config&&page==='homepage')render();}}
function homepageHTML(){
  const home=config.homepage;if(homepageUsers===null&&!homepageUsersLoading&&!homepageUsersError)loadHomepageUsers();
  return heading('GATEHOMEPAGE','浏览器首页','管理首页服务与账号。桌面内容、组件和外观在 GateHomePage 内编辑。',`<a class="secondary inline-icon-link" href="${esc(homepageAddress())}" target="_blank" rel="noopener noreferrer">${icon('external-link')}打开 Page</a>`)+
    `<section class="panel"><div class="panel-heading"><h2>首页服务</h2>${badge(home.enabled?'已开启':'已关闭',home.enabled?'':'gray')}</div><div class="hp-service-body"><form data-homepage="true" data-kind="listener"><div class="toggle-row"><div><b>启用 GateHomePage</b><p>开关和监听端口变更在重启后生效，用户桌面保留。</p></div><label class="switch"><input name="enabled" type="checkbox" ${home.enabled?'checked':''}><span></span><span class="sr-only">启用首页</span></label></div><label>首页端口<input name="port" type="number" min="1024" max="65535" value="${home.port}" required></label><p class="form-note">Page 数据保存于 data/page/，随 /data 持久化和完整备份保留。</p><p class="error" role="alert"></p><button type="submit" class="primary">保存服务设置</button>${status.restart_required?'<span class="badge amber">监听变更需要重启</span>':''}</form></div></section>`+
    `<section class="panel"><div class="panel-heading"><div><h2>Page 账号</h2><p class="form-note">每个账号拥有独立桌面。这些账号只用于首页，不是反代服务的访问账号。</p></div><button type="button" class="primary" data-hp-action="user-new">${icon('plus')}添加账号</button></div>${homepageUsersError?`<div class="hp-service-body"><p class="error">${esc(homepageUsersError)}</p><button type="button" class="secondary" data-hp-action="users-reload">重试</button></div>`:homepageUsers===null?'<p class="form-note hp-service-body">正在读取账号…</p>':`<div class="table-wrap"><table><thead><tr><th>账号</th><th>桌面</th><th>状态</th><th>操作</th></tr></thead><tbody>${homepageUsers.map(user=>`<tr><td><b>${esc(user.username)}</b>${user.admin?'<div class="form-note">GateHome 管理员</div>':''}</td><td>${user.admin?'管理员桌面':'独立桌面'}</td><td>${badge(user.enabled?'可登录':'已停用',user.enabled?'':'gray')}</td><td>${user.admin?'<span class="form-note">账号在右上角管理</span>':`<button type="button" class="secondary" data-hp-action="user-edit" data-id="${esc(user.id)}">${icon('edit')}编辑账号</button>`}</td></tr>`).join('')}</tbody></table></div>`}</section>`;
}
function homepageUserDialog(id=''){
  const user=homepageUsers?.find(u=>u.id===id);let dialog=$('#homepage-user-dialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='homepage-user-dialog';dialog.addEventListener('close',()=>dialog.querySelector('form')?.reset());document.body.append(dialog);}
  dialog.innerHTML=`<form data-homepage="true" data-kind="user" data-id="${esc(id)}"><div class="dialog-heading"><div><span class="eyebrow">GATEHOMEPAGE</span><h2>${user?'编辑首页账号':'添加首页账号'}</h2></div><button type="button" class="icon-button" data-action="close-dialog" aria-label="关闭">${icon('close')}</button></div><div class="dialog-body"><label>首页账号<input name="username" value="${esc(user?.username||'')}" maxlength="64" autocomplete="off" required></label><label>${user?'新密码':'首页密码'}<input name="password" type="password" maxlength="72" autocomplete="new-password" ${user?'':'required'}><small>12–72 字节。${user?'留空保留现有密码。':''}</small></label><label>确认密码<input name="confirm_password" type="password" maxlength="72" autocomplete="new-password" ${user?'':'required'}></label><label class="check-label"><input name="enabled" type="checkbox" ${!user||user.enabled?'checked':''}>允许此账号登录 Page</label><p class="form-note">停用或修改账号后，此用户已有的 Page 登录会话立即失效。桌面内容会保留。</p><p class="error" role="alert"></p></div><div class="dialog-actions"><button type="button" class="secondary" data-action="close-dialog">取消</button><button type="submit" class="primary">保存账号</button></div></form>`;
  dialog.setAttribute('aria-label',user?'编辑首页账号':'添加首页账号');hydrateIcons(dialog);openDialog(dialog);
}
document.addEventListener('click',event=>{const target=event.target.closest('[data-hp-action]');if(!target||busy||!config)return;const action=target.dataset.hpAction;if(action==='user-new')homepageUserDialog();if(action==='user-edit')homepageUserDialog(target.dataset.id);if(action==='users-reload')loadHomepageUsers();});
document.addEventListener('submit',event=>{
  const form=event.target;if(!form.dataset.homepage)return;event.preventDefault();submitForm(form,async()=>{
    const e=form.elements;if(form.dataset.kind==='listener'){applyConfig(await api('homepage','PUT',{enabled:e.enabled.checked,port:Number(e.port.value),revision}));homepageUsersRevision=revision;await refreshStatus();render();toast('首页服务设置已保存'+(status.restart_required?'，重启后生效':''));return;}
    const password=e.password.value;if(password!==e.confirm_password.value)throw new Error('两次首页密码不一致');const size=new TextEncoder().encode(password).length;if((password||!form.dataset.id)&&(size<12||size>72))throw new Error('首页密码须为 12–72 字节');
    const result=await api('homepage/users'+(form.dataset.id?'/'+form.dataset.id:''),form.dataset.id?'PUT':'POST',{username:e.username.value.trim(),password,enabled:e.enabled.checked,revision:homepageUsersRevision});e.password.value='';e.confirm_password.value='';homepageUsers=result.users;homepageUsersRevision=result.revision;applyConfig(await api('config'));closeDialog(form.closest('dialog'));render();toast('首页账号已保存');
  });
});
