import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const source=readFileSync(new URL('../internal/gateway/web/app.js',import.meta.url),'utf8');
const helpers=source.slice(source.indexOf("let adminUsername='';"),source.indexOf('async function api('));
const field=value=>({value,focus(){this.focused=true;}});
const form={elements:{username:field('TEST_ONLY_OWNER'),current_password:field('TEST_ONLY_CURRENT_PASSWORD'),new_password:field('TEST_ONLY_NEW_PASSWORD'),confirm_password:field('TEST_ONLY_NEW_PASSWORD')}};
const login={elements:{username:field('admin'),password:field('')}};
const elements={'#account-form':form,'#login-form':login,'#login-error':{textContent:''},'#account-name':{textContent:''},'#account-avatar':{textContent:''},'#account-button':{setAttribute(){}}};
let loggedOut=false;
const context=vm.createContext({TextEncoder,$:key=>elements[key],busy:false,form,showLogin:()=>{loggedOut=true;},toast:()=>{},api:async()=>({username:'TEST_ONLY_OWNER',message:'TEST_ONLY_CHANGED'})});
vm.runInContext(helpers,context);
const run=expression=>vm.runInContext(expression,context);
assert.deepEqual(structuredClone(run('accountInput(form)')),{username:'TEST_ONLY_OWNER',current_password:'TEST_ONLY_CURRENT_PASSWORD',new_password:'TEST_ONLY_NEW_PASSWORD',confirm_password:'TEST_ONLY_NEW_PASSWORD'});
form.elements.confirm_password.value='TEST_ONLY_DIFFERENT';assert.throws(()=>run('accountInput(form)'),/不一致/);
form.elements.new_password.value='short';form.elements.confirm_password.value='short';assert.throws(()=>run('accountInput(form)'),/12–72/);
form.elements.new_password.value='';form.elements.confirm_password.value='';assert.equal(run('accountInput(form).new_password'),'');
form.elements.username.value=' 管理';assert.throws(()=>run('accountInput(form)'),/管理员账号/);
form.elements.username.value='中'.repeat(22);assert.throws(()=>run('accountInput(form)'),/管理员账号/);
form.elements.username.value='TEST_ONLY_OWNER';form.elements.new_password.value='TEST_ONLY_NEW_PASSWORD';form.elements.confirm_password.value='TEST_ONLY_NEW_PASSWORD';
await run('saveAdminAccount(form)');assert.equal(loggedOut,true);assert.equal(login.elements.username.value,'TEST_ONLY_OWNER');assert.ok(login.elements.password.focused);
for(const name of ['current_password','new_password','confirm_password']) assert.equal(form.elements[name].value,'','successful request retained a password');
loggedOut=false;
form.elements.current_password.value='TEST_ONLY_CURRENT_PASSWORD';context.api=async()=>{throw new Error('TEST_ONLY_FAILURE');};
await assert.rejects(run('saveAdminAccount(form)'),/TEST_ONLY_FAILURE/);assert.equal(loggedOut,false);assert.equal(form.elements.current_password.value,'','failed request retained current password');
run("applyAccount({username:'<script>TEST</script>'})");assert.equal(elements['#account-name'].textContent,'<script>TEST</script>');
const html=readFileSync(new URL('../internal/gateway/web/index.html',import.meta.url),'utf8');
assert.match(html,/<details id="account-menu"[\s\S]*?<summary id="account-button"[^>]*aria-controls="account-menu-items"[\s\S]*?data-action="edit-admin-account"[\s\S]*?修改密码[\s\S]*?data-action="logout"[\s\S]*?退出登录/);
assert.match(html,/id="login-form"[\s\S]*?name="username"/);
assert.match(html,/id="account-dialog"[\s\S]*?name="current_password"[\s\S]*?name="new_password"[\s\S]*?name="confirm_password"/);
assert.match(source,/if\(dialog.id==='account-dialog'\) clearAccountPasswords\(\)/);
console.log('Management account form: current-password verification fields, byte limits, confirmation, username-only changes, secret clearing, relogin and text-only rendering PASS');
